apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kafka
    repo: https://charts.bitnami.com/bitnami
    version: 32.4.0
    releaseName: kafka
    valuesFile: values.yaml