apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../k8s-manifests
namePrefix: orderservice-
labels:
  - includeSelectors: true
    pairs:
      app-name: orderservice
      app-env: development
replicas:
  - count: 1
    name: deploy
images:
  - name: registry/image:tag
    newName: k3d-ticketing-registry:5000/orderservice
    newTag: latest
configMapGenerator:
  - name: config-map
    files:
      - application.properties
generatorOptions:
  labels:
    app-type: spring-boot
patches:
  - target:
      kind: Deployment
      name: deploy
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: orderservice
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts/0/name
        value: orderservice-config-volume
      - op: replace
        path: /spec/template/spec/volumes/0/name
        value: orderservice-config-volume