apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ticketing
servers: 1
agents: 2
ports:
  - port: 8080:8080
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: k3d-ticketing-registry
    host: "0.0.0.0"
    hostPort: "5000"
options:
  k3s:
    extraArgs:
      - arg: "--node-taint=node-role.kubernetes.io/control-plane=true:NoSchedule"
        nodeFilters:
          - server:*