apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: mysql
    repo: https://charts.bitnami.com/bitnami
    version: 14.0.0
    releaseName: mysql
    valuesFile: values.yaml