architecture: standalone
auth:
  createDatabase: true
  database: "ticketing"
  username: "appuser"
  password: "password"
primary:
  resourcesPreset: "small"
  persistence:
    enabled: false
    size: 1Gi
  service:
    type: LoadBalancer
    ports:
      mysql: 3306