apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app-type: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app-type: spring-boot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app-type: spring-boot
    spec:
      containers:
        - name: spring-boot-app
          image: registry/image:tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 128m
              memory: 256Mi
            limits:
              cpu: 256m
              memory: 512Mi
          env:
            - name: spring.config.location
              value: /config/application.properties
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: config-map

      